# Generated by Django 6.0.4 on 2026-04-24 13:54

import django.db.models.deletion
from django.db import migrations, models


def migrate_document_categories(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    DocumentCategory = apps.get_model('documents', 'DocumentCategory')

    default_category, _ = DocumentCategory.objects.get_or_create(name='Uncategorized')

    categories = {}
    for raw_value in Document.objects.values_list('category', flat=True).distinct():
        name = (raw_value or '').strip()
        if not name:
            categories[name] = default_category.id
            continue
        category, _ = DocumentCategory.objects.get_or_create(name=name)
        categories[name] = category.id

    for document in Document.objects.all():
        name = (document.category or '').strip()
        document.category = str(categories.get(name, default_category.id))
        document.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(migrate_document_categories, migrations.RunPython.noop),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_user_id_a8f8c0_idx',
            old_name='documents_d_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_documen_40c475_idx',
            old_name='documents_d_document_type_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_categor_fec314_idx',
            old_name='documents_d_category_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for organizing documents (e.g., Interview Preparation, Research, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory'),
        ),
    ]
