# Generated by Django 6.0.4 on 2026-04-12 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_answer_evaluation_status_interview_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCoachSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('subtopics', models.JSONField(default=list)),
                ('selected_subtopic', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(choices=[('subtopic_selection', 'Subtopic Selection'), ('questioning', 'Questioning'), ('completed', 'Completed')], default='subtopic_selection', max_length=50)),
                ('current_question', models.TextField(blank=True)),
                ('mastery_score', models.PositiveIntegerField(default=0)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('suggested_next_subtopic', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_coach_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
