# Generated by Django 6.0.4 on 2026-04-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_personalcoachsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCoachAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user_answer', models.TextField()),
                ('score', models.PositiveIntegerField()),
                ('strengths', models.JSONField(default=list)),
                ('gaps', models.JSONField(default=list)),
                ('feedback', models.TextField(blank=True)),
                ('coach_decision', models.CharField(choices=[('advance', 'Advance'), ('remediate', 'Remediate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='interviews.personalcoachsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
