# Generated by Django 6.0.4 on 2026-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_personalcoachattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcoachsession',
            name='current_lesson',
            field=models.TextField(blank=True),
        ),
    ]
