# Generated by Django 6.0.4 on 2026-04-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_useraspiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspirationChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aspiration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='interviews.useraspiration')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
