from django.urls import path

from .views import (
    analyze_job_description,
    answer_personal_coach_question,
    answer_hr_voice_interview,
    candidate_profile_settings,
    choose_personal_coach_subtopic,
    choose_personal_coach_lesson,
    create_user_aspiration,
    explain_personal_coach_query,
    generate_aspiration_checklist,
    interview_summary,
    next_question,
    register,
    resume_job_description_analysis,
    resume_user_aspiration,
    resume_hr_voice_interview,
    resume_personal_coach_session,
    start_hr_voice_interview,
    start_interview,
    start_personal_coach,
    submit_answer,
    toggle_aspiration_checklist_item,
    user_learning_progress,
)

urlpatterns = [
    path("auth/register/", register, name="register"),
    path("start/", start_interview, name="start_interview"),
    path("<int:interview_id>/next/", next_question, name="next_question"),
    path("answer/", submit_answer, name="submit_answer"),
    path("<int:interview_id>/summary/", interview_summary, name="interview_summary"),
    path("progress/", user_learning_progress, name="user_learning_progress"),
    path("job-analyzer/analyze/", analyze_job_description, name="analyze_job_description"),
    path(
        "job-analyzer/<int:analysis_id>/resume/",
        resume_job_description_analysis,
        name="resume_job_description_analysis",
    ),
    path("aspiration/create/", create_user_aspiration, name="create_user_aspiration"),
    path("aspiration/<int:aspiration_id>/resume/", resume_user_aspiration, name="resume_user_aspiration"),
    path(
        "aspiration/<int:aspiration_id>/checklist/generate/",
        generate_aspiration_checklist,
        name="generate_aspiration_checklist",
    ),
    path(
        "aspiration/<int:aspiration_id>/checklist/toggle/",
        toggle_aspiration_checklist_item,
        name="toggle_aspiration_checklist_item",
    ),
    path("profile/settings/", candidate_profile_settings, name="candidate_profile_settings"),
    path("hr-voice/start/", start_hr_voice_interview, name="start_hr_voice_interview"),
    path("hr-voice/<int:session_id>/answer/", answer_hr_voice_interview, name="answer_hr_voice_interview"),
    path("hr-voice/<int:session_id>/resume/", resume_hr_voice_interview, name="resume_hr_voice_interview"),
    path("coach/start/", start_personal_coach, name="start_personal_coach"),
    path(
        "coach/<int:session_id>/choose-subtopic/",
        choose_personal_coach_subtopic,
        name="choose_personal_coach_subtopic",
    ),
    path(
        "coach/<int:session_id>/choose-lesson/",
        choose_personal_coach_lesson,
        name="choose_personal_coach_lesson",
    ),
    path(
        "coach/<int:session_id>/answer/",
        answer_personal_coach_question,
        name="answer_personal_coach_question",
    ),
    path(
        "coach/<int:session_id>/explain/",
        explain_personal_coach_query,
        name="explain_personal_coach_query",
    ),
    path(
        "coach/<int:session_id>/resume/",
        resume_personal_coach_session,
        name="resume_personal_coach_session",
    ),
]
