package com.asknehru.interviewsimulator.service;

import com.asknehru.interviewsimulator.model.*;
import com.asknehru.interviewsimulator.repository.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;

@Service
@RequiredArgsConstructor
@Slf4j
public class PersonalCoachService {

    private final LlmService llmService;
    private final PersonalCoachSessionRepository sessionRepository;
    private final PersonalCoachAttemptRepository attemptRepository;
    private final TopicRepository topicRepository;
    private final GeneratedContentCacheRepository generatedContentCacheRepository;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @Transactional
    public Map<String, Object> startOrResumeSession(User user, String topic, String note) {
        Topic topicEntity = topicRepository.findByUserAndName(user, topic)
                .orElseGet(() -> topicRepository.save(Topic.builder()
                        .user(user)
                        .name(topic)
                        .description("Autogenerated default topic")
                        .build()));

        PersonalCoachSession session;
        if (note != null && !note.trim().isEmpty()) {
            String cacheKey = note.trim();
            Optional<GeneratedContentCache> cacheOpt = generatedContentCacheRepository
                    .findByTopicAndContentTypeAndKey(topicEntity, "COACH_SUBTOPICS", cacheKey);

            List<String> subtopics;
            if (cacheOpt.isPresent()) {
                subtopics = deserializeList(cacheOpt.get().getContent());
                log.info("Serving coach subtopics for topic '{}' (instructions: {}) from cache.", topic, cacheKey);
            } else {
                subtopics = generateSubtopics(topic, note);
                GeneratedContentCache cache = GeneratedContentCache.builder()
                        .user(user)
                        .topic(topicEntity)
                        .contentType("COACH_SUBTOPICS")
                        .key(cacheKey)
                        .content(serialize(subtopics))
                        .build();
                generatedContentCacheRepository.save(cache);
            }

            PersonalCoachSession s = PersonalCoachSession.builder()
                    .user(user)
                    .topic(topic)
                    .subtopics(serialize(subtopics))
                    .stage(PersonalCoachSession.Stage.SUBTOPIC_SELECTION)
                    .build();
            session = sessionRepository.save(s);
        } else {
            session = sessionRepository.findFirstByUserAndTopicOrderByIdDesc(user, topic)
                    .orElseGet(() -> {
                        Optional<GeneratedContentCache> cacheOpt = generatedContentCacheRepository
                                .findByTopicAndContentTypeAndKey(topicEntity, "COACH_SUBTOPICS", "");

                        List<String> subtopics;
                        if (cacheOpt.isPresent()) {
                            subtopics = deserializeList(cacheOpt.get().getContent());
                            log.info("Serving coach subtopics for topic '{}' from cache.", topic);
                        } else {
                            subtopics = generateSubtopics(topic, null);
                            GeneratedContentCache cache = GeneratedContentCache.builder()
                                    .user(user)
                                    .topic(topicEntity)
                                    .contentType("COACH_SUBTOPICS")
                                    .key("")
                                    .content(serialize(subtopics))
                                    .build();
                            generatedContentCacheRepository.save(cache);
                        }

                        PersonalCoachSession s = PersonalCoachSession.builder()
                                .user(user)
                                .topic(topic)
                                .subtopics(serialize(subtopics))
                                .stage(PersonalCoachSession.Stage.SUBTOPIC_SELECTION)
                                .build();
                        return sessionRepository.save(s);
                    });
        }
        
        Map<String, Object> response = new HashMap<>();
        response.put("session_id", session.getId());
        response.put("topic", session.getTopic());
        response.put("subtopics", deserializeList(session.getSubtopics()));
        response.put("stage", session.getStage() != null ? session.getStage().name() : "SUBTOPIC_SELECTION");
        response.put("coach_prompt", "Choose one subtopic to begin learning.");
        return response;
    }

    public PersonalCoachSession getSession(Long sessionId) {
        return sessionRepository.findById(sessionId)
            .orElseThrow(() -> new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND, "Session not found"));
    }

    public Map<String, Object> getSessionData(Long sessionId) {
        PersonalCoachSession session = getSession(sessionId);
        Map<String, Object> response = new HashMap<>();
        response.put("session_id", session.getId());
        response.put("topic", session.getTopic());
        response.put("subtopics", deserializeList(session.getSubtopics()));
        response.put("lessons_by_subtopic", deserializeMap(session.getLessonsBySubtopic()));
        response.put("selected_subtopic", session.getSelectedSubtopic());
        response.put("selected_lesson", session.getSelectedLesson());
        response.put("stage", session.getStage() != null ? session.getStage().name() : "");
        response.put("lesson", session.getCurrentLesson());
        response.put("question", session.getCurrentQuestion());
        response.put("attempt_count", session.getAttemptCount() != null ? session.getAttemptCount() : 0);
        response.put("coach_prompt", "Resume your learning journey.");
        
        if (session.getSelectedSubtopic() != null) {
            Map<String, List<String>> map = deserializeMap(session.getLessonsBySubtopic());
            response.put("available_lessons", map.getOrDefault(session.getSelectedSubtopic(), new ArrayList<>()));
        }

        List<PersonalCoachAttempt> attempts = attemptRepository.findBySessionOrderByCreatedAtDesc(session);
        List<String> practicedSubtopics = attempts.stream()
            .map(PersonalCoachAttempt::getSubtopic)
            .filter(s -> s != null && !s.isEmpty())
            .distinct().toList();
        response.put("practiced_subtopics", practicedSubtopics);
        
        if (session.getSelectedSubtopic() != null) {
            List<String> practicedLessons = attempts.stream()
                .filter(a -> session.getSelectedSubtopic().equals(a.getSubtopic()))
                .map(PersonalCoachAttempt::getLesson)
                .filter(l -> l != null && !l.isEmpty())
                .distinct().toList();
            response.put("practiced_lessons", practicedLessons);
        }

        attempts.stream().max(Comparator.comparing(PersonalCoachAttempt::getId)).ifPresent(latest -> {
            Map<String, Object> lat = new HashMap<>();
            lat.put("score", latest.getScore());
            lat.put("strengths", deserializeList(latest.getStrengths()));
            lat.put("gaps", deserializeList(latest.getGaps()));
            lat.put("feedback", latest.getFeedback());
            lat.put("coach_decision", latest.getCoachDecision().name());
            response.put("latest_attempt", lat);
        });

        Map<String, List<String>> practicedLessonsMap = new HashMap<>();
        for (PersonalCoachAttempt attempt : attempts) {
            if (attempt.getSubtopic() != null && attempt.getLesson() != null) {
                practicedLessonsMap.computeIfAbsent(attempt.getSubtopic(), k -> new ArrayList<>())
                                   .add(attempt.getLesson());
            }
        }
        practicedLessonsMap.replaceAll((k, v) -> v.stream().distinct().toList());
        response.put("practiced_lessons_map", practicedLessonsMap);

        return response;
    }

    public List<String> generateSubtopics(String topic, String note) {
        String notePrompt = (note != null && !note.trim().isEmpty())
                ? String.format("\nAdditional instructions/preferences from user: %s\n", note)
                : "";
        String prompt = String.format(
            "You are a personal interview coach.\n" +
            "Generate a clean list of subtopics for topic: %s\n%s\n" +
            "Rules:\n" +
            "- Return only subtopic names.\n" +
            "- Count can vary (typically 6 to 20).\n" +
            "- Do not number lines or add explanations.\n",
            topic, notePrompt
        );

        String raw = llmService.generate(prompt);
        List<String> lines = extractLines(raw);
        if (lines.size() >= 4) return lines;

        throw new org.springframework.web.server.ResponseStatusException(
            org.springframework.http.HttpStatus.SERVICE_UNAVAILABLE, 
            "Failed to generate subtopics from AI. Please check your API key and connection."
        );
    }

    @Transactional
    public Map<String, Object> chooseSubtopic(Long sessionId, String subtopic) {
        PersonalCoachSession session = sessionRepository.findById(sessionId).orElseThrow();
        session.setSelectedSubtopic(subtopic);
        
        Topic topicEntity = topicRepository.findByUserAndName(session.getUser(), session.getTopic())
                .orElseGet(() -> topicRepository.save(Topic.builder()
                        .user(session.getUser())
                        .name(session.getTopic())
                        .description("Autogenerated default topic")
                        .build()));

        Optional<GeneratedContentCache> cacheOpt = generatedContentCacheRepository
                .findByTopicAndContentTypeAndKey(topicEntity, "COACH_LESSONS", subtopic.trim());

        List<String> lessons;
        if (cacheOpt.isPresent()) {
            lessons = deserializeList(cacheOpt.get().getContent());
            log.info("Serving coach lessons list for subtopic '{}' from cache.", subtopic);
        } else {
            lessons = generateLessons(session.getTopic(), subtopic);
            GeneratedContentCache cache = GeneratedContentCache.builder()
                    .user(session.getUser())
                    .topic(topicEntity)
                    .contentType("COACH_LESSONS")
                    .key(subtopic.trim())
                    .content(serialize(lessons))
                    .build();
            generatedContentCacheRepository.save(cache);
        }

        Map<String, List<String>> lessonsMap = deserializeMap(session.getLessonsBySubtopic());
        lessonsMap.put(subtopic, lessons);
        
        session.setLessonsBySubtopic(serialize(lessonsMap));
        session.setStage(PersonalCoachSession.Stage.LESSON_SELECTION);
        sessionRepository.save(session);
        
        return Map.of(
            "session_id", session.getId(),
            "topic", session.getTopic(),
            "subtopic", subtopic,
            "lessons", lessons,
            "practiced_subtopics", attemptRepository.findBySessionOrderByCreatedAtDesc(session).stream()
                    .map(PersonalCoachAttempt::getSubtopic)
                    .filter(s -> s != null && !s.isEmpty())
                    .distinct()
                    .toList(),
            "practiced_lessons", attemptRepository.findBySessionOrderByCreatedAtDesc(session).stream()
                    .filter(a -> subtopic.equals(a.getSubtopic()))
                    .map(PersonalCoachAttempt::getLesson)
                    .filter(l -> l != null && !l.isEmpty())
                    .distinct()
                    .toList(),
            "stage", session.getStage().name(),
            "coach_prompt", "You are now learning '" + subtopic + "'. Please select a specific lesson below to continue."
        );
    }

    public List<String> generateLessons(String topic, String subtopic) {
        String prompt = String.format(
            "You are a personal coach creating lesson modules.\n" +
            "Topic: %s, Subtopic: %s\n\n" +
            "Return STRICT JSON only:\n" +
            "{\"lessons\": [\"Lesson title 1\", \"Lesson title 2\"]}",
            topic, subtopic
        );

        String raw = llmService.generate(prompt);
        JsonNode parsed = llmService.safeJsonLoads(raw);
        List<String> lessons = normalizeList(parsed.path("lessons"));
        if (lessons.size() >= 3) return lessons;

        throw new org.springframework.web.server.ResponseStatusException(
            org.springframework.http.HttpStatus.SERVICE_UNAVAILABLE, 
            "Failed to generate lessons from AI. Please check your API key and connection."
        );
    }

    @Transactional
    public Map<String, Object> chooseLesson(Long sessionId, String lesson) {
        PersonalCoachSession session = sessionRepository.findById(sessionId).orElseThrow();
        session.setSelectedLesson(lesson);

        Topic topicEntity = topicRepository.findByUserAndName(session.getUser(), session.getTopic())
                .orElseGet(() -> topicRepository.save(Topic.builder()
                        .user(session.getUser())
                        .name(session.getTopic())
                        .description("Autogenerated default topic")
                        .build()));

        String cacheKey = session.getSelectedSubtopic() + ":" + lesson;
        Optional<GeneratedContentCache> cacheOpt = generatedContentCacheRepository
                .findByTopicAndContentTypeAndKey(topicEntity, "COACH_LESSON_DETAILS", cacheKey);

        String lessonText;
        String questionJson;

        if (cacheOpt.isPresent()) {
            try {
                JsonNode parsed = objectMapper.readTree(cacheOpt.get().getContent());
                lessonText = parsed.path("lesson").asText();
                if (parsed.has("questions")) {
                    questionJson = parsed.path("questions").toString();
                } else {
                    questionJson = parsed.path("question").asText();
                }
                log.info("Serving coach lesson content and MCQs for '{}' from cache.", cacheKey);
            } catch (Exception e) {
                log.error("Failed to parse cached lesson details for '{}', regenerating: {}", cacheKey, e.getMessage());
                return chooseLessonRegenerate(session, topicEntity, lesson, cacheKey);
            }
        } else {
            return chooseLessonRegenerate(session, topicEntity, lesson, cacheKey);
        }

        session.setCurrentLesson(lessonText);
        session.setCurrentQuestion(questionJson);
        session.setStage(PersonalCoachSession.Stage.QUESTIONING);
        sessionRepository.save(session);

        return Map.of("lesson", lessonText, "question", questionJson);
    }

    private Map<String, Object> chooseLessonRegenerate(PersonalCoachSession session, Topic topicEntity, String lesson, String cacheKey) {
        String prompt = String.format(
            "You are a personal interview coach. Provide a detailed lesson and exactly 5 multiple choice questions (MCQs) based on the lesson to test the candidate.\n" +
            "Topic: %s\n" +
            "Subtopic: %s\n" +
            "Lesson: %s\n\n" +
            "Return STRICT JSON:\n" +
            "{\n" +
            "  \"lesson\": \"Detailed markdown content paragraphs explaining this lesson\",\n" +
            "  \"questions\": [\n" +
            "    {\n" +
            "      \"question\": \"Question text 1\",\n" +
            "      \"options\": [\"Option 1\", \"Option 2\", \"Option 3\", \"Option 4\"],\n" +
            "      \"correctAnswer\": \"Option 1\",\n" +
            "      \"explanation\": \"Brief explanation of why Option 1 is correct\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"question\": \"Question text 2\",\n" +
            "      \"options\": [\"Option 1\", \"Option 2\", \"Option 3\", \"Option 4\"],\n" +
            "      \"correctAnswer\": \"Option 2\",\n" +
            "      \"explanation\": \"Brief explanation of why Option 2 is correct\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"question\": \"Question text 3\",\n" +
            "      \"options\": [\"Option 1\", \"Option 2\", \"Option 3\", \"Option 4\"],\n" +
            "      \"correctAnswer\": \"Option 3\",\n" +
            "      \"explanation\": \"Brief explanation of why Option 3 is correct\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"question\": \"Question text 4\",\n" +
            "      \"options\": [\"Option 1\", \"Option 2\", \"Option 3\", \"Option 4\"],\n" +
            "      \"correctAnswer\": \"Option 4\",\n" +
            "      \"explanation\": \"Brief explanation of why Option 4 is correct\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"question\": \"Question text 5\",\n" +
            "      \"options\": [\"Option 1\", \"Option 2\", \"Option 3\", \"Option 4\"],\n" +
            "      \"correctAnswer\": \"Option 1\",\n" +
            "      \"explanation\": \"Brief explanation of why Option 1 is correct\"\n" +
            "    }\n" +
            "  ]\n" +
            "}\n\n" +
            "Rules:\n" +
            "- You must provide EXACTLY 5 questions.\n" +
            "- Each question must have exactly 4 choices in \"options\".\n" +
            "- \"correctAnswer\" must match one of the choices in \"options\" exactly.\n" +
            "- Return only the JSON object, no extra text.",
            session.getTopic(), session.getSelectedSubtopic(), lesson
        );

        String raw = llmService.generate(prompt);
        JsonNode parsed = llmService.safeJsonLoads(raw);
        
        if (!parsed.has("lesson") || (!parsed.has("questions") && !parsed.has("question"))) {
            throw new org.springframework.web.server.ResponseStatusException(
                org.springframework.http.HttpStatus.SERVICE_UNAVAILABLE, 
                "Failed to generate lesson content from AI."
            );
        }

        String lessonText = parsed.path("lesson").asText();
        String questionJson;
        if (parsed.has("questions")) {
            questionJson = parsed.path("questions").toString();
        } else {
            questionJson = parsed.path("question").asText();
        }

        if (raw != null && !raw.trim().isEmpty()) {
            GeneratedContentCache cache = GeneratedContentCache.builder()
                    .user(session.getUser())
                    .topic(topicEntity)
                    .contentType("COACH_LESSON_DETAILS")
                    .key(cacheKey)
                    .content(raw)
                    .build();
            generatedContentCacheRepository.save(cache);
        }

        session.setCurrentLesson(lessonText);
        session.setCurrentQuestion(questionJson);
        session.setStage(PersonalCoachSession.Stage.QUESTIONING);
        sessionRepository.save(session);

        return Map.of("lesson", lessonText, "question", questionJson);
    }

    @Transactional
    public Map<String, Object> evaluateAnswer(Long sessionId, String answerText) {
        PersonalCoachSession session = sessionRepository.findById(sessionId).orElseThrow();
        
        String currentQuestion = session.getCurrentQuestion();
        boolean isMcq = false;
        List<Map<String, Object>> mcqs = null;
        try {
            if (currentQuestion != null && (currentQuestion.trim().startsWith("[") || currentQuestion.trim().startsWith("{"))) {
                String jsonToParse = currentQuestion.trim();
                if (jsonToParse.startsWith("{")) {
                    JsonNode node = objectMapper.readTree(jsonToParse);
                    if (node.has("questions")) {
                        node = node.path("questions");
                    }
                    mcqs = objectMapper.convertValue(node, new TypeReference<List<Map<String, Object>>>() {});
                } else {
                    mcqs = objectMapper.readValue(jsonToParse, new TypeReference<List<Map<String, Object>>>() {});
                }
                isMcq = mcqs != null && !mcqs.isEmpty();
            }
        } catch (Exception e) {
            log.warn("Failed to parse current question as MCQ JSON: {}", e.getMessage());
        }

        if (isMcq) {
            List<String> userAnswers = new ArrayList<>();
            try {
                userAnswers = objectMapper.readValue(answerText, new TypeReference<List<String>>() {});
            } catch (Exception e) {
                // fallback to treat answerText as a single string
                userAnswers.add(answerText);
            }

            int correctCount = 0;
            List<String> strengths = new ArrayList<>();
            List<String> gaps = new ArrayList<>();
            StringBuilder feedbackBuilder = new StringBuilder();

            for (int i = 0; i < mcqs.size(); i++) {
                Map<String, Object> mcq = mcqs.get(i);
                String qText = (String) mcq.get("question");
                String correctAnswer = (String) mcq.get("correctAnswer");
                String explanation = (String) mcq.get("explanation");
                
                String userAns = (i < userAnswers.size()) ? userAnswers.get(i) : "";
                
                boolean isCorrect = false;
                if (correctAnswer != null && userAns != null) {
                    isCorrect = correctAnswer.trim().equalsIgnoreCase(userAns.trim());
                }
                
                if (isCorrect) {
                    correctCount++;
                    strengths.add("Q" + (i + 1) + ": \"" + qText + "\" - Correctly answered: " + correctAnswer);
                } else {
                    gaps.add("Q" + (i + 1) + ": \"" + qText + "\" - Missed. You selected: " + (userAns.isEmpty() ? "(No answer)" : userAns) + ". Correct answer: " + correctAnswer + ". " + (explanation != null ? explanation : ""));
                }
            }

            int score = (int) Math.round((double) correctCount / mcqs.size() * 100);
            PersonalCoachAttempt.CoachDecision coachDecision = (score >= 60) ? 
                    PersonalCoachAttempt.CoachDecision.ADVANCE : PersonalCoachAttempt.CoachDecision.REMEDIATE;

            feedbackBuilder.append(String.format("You got %d out of %d questions correct (%d%%).\n\n", correctCount, mcqs.size(), score));
            if (score >= 60) {
                feedbackBuilder.append("Great job! You have demonstrated good understanding of this lesson. You can now advance to the next subtopic or lesson.");
            } else {
                feedbackBuilder.append("Let's review the concepts. You can try the lesson again or ask questions in the explanation section to clarify any confusion.");
            }

            PersonalCoachAttempt attempt = PersonalCoachAttempt.builder()
                    .session(session)
                    .subtopic(session.getSelectedSubtopic())
                    .lesson(session.getSelectedLesson())
                    .question(session.getCurrentQuestion())
                    .userAnswer(answerText)
                    .score(score)
                    .strengths(serialize(strengths))
                    .gaps(serialize(gaps))
                    .feedback(feedbackBuilder.toString())
                    .coachDecision(coachDecision)
                    .build();
            attemptRepository.save(attempt);

            int currentAttemptCount = session.getAttemptCount() != null ? session.getAttemptCount() : 0;
            session.setAttemptCount(currentAttemptCount + 1);
            
            int currentMastery = session.getMasteryScore() != null ? session.getMasteryScore() : score;
            session.setMasteryScore(currentAttemptCount == 0 ? score : (currentMastery + score) / 2);
            
            if (coachDecision == PersonalCoachAttempt.CoachDecision.ADVANCE) {
                session.setStage(PersonalCoachSession.Stage.LESSON_SELECTION);
            }
            sessionRepository.save(session);

            return Map.of(
                "score", score,
                "feedback", attempt.getFeedback(),
                "decision", coachDecision.name(),
                "strengths", strengths,
                "gaps", gaps
            );
        }

        // Legacy fallback
        String prompt = String.format(
            "Topic: %s, Subtopic: %s, Question: %s, Answer: %s\n\n" +
            "Return STRICT JSON: {\"score\": 0-100, \"strengths\": [], \"gaps\": [], \"feedback\": \"\", \"coach_decision\": \"advance|remediate\"}",
            session.getTopic(), session.getSelectedSubtopic(), session.getCurrentQuestion(), answerText
        );

        String raw = llmService.generate(prompt);
        JsonNode parsed = llmService.safeJsonLoads(raw);

        if (!parsed.has("score") || !parsed.has("coach_decision")) {
            throw new org.springframework.web.server.ResponseStatusException(
                org.springframework.http.HttpStatus.SERVICE_UNAVAILABLE, 
                "Failed to generate evaluation from AI. Please check your API key and connection."
            );
        }

        int score = parsed.path("score").asInt();
        String decision = parsed.path("coach_decision").asText().toUpperCase();
        PersonalCoachAttempt.CoachDecision coachDecision = decision.equals("ADVANCE") ? 
                PersonalCoachAttempt.CoachDecision.ADVANCE : PersonalCoachAttempt.CoachDecision.REMEDIATE;

        PersonalCoachAttempt attempt = PersonalCoachAttempt.builder()
                .session(session)
                .subtopic(session.getSelectedSubtopic())
                .lesson(session.getSelectedLesson())
                .question(session.getCurrentQuestion())
                .userAnswer(answerText)
                .score(score)
                .strengths(serialize(normalizeList(parsed.path("strengths"))))
                .gaps(serialize(normalizeList(parsed.path("gaps"))))
                .feedback(parsed.path("feedback").asText())
                .coachDecision(coachDecision)
                .build();
        attemptRepository.save(attempt);

        int currentAttemptCount = session.getAttemptCount() != null ? session.getAttemptCount() : 0;
        session.setAttemptCount(currentAttemptCount + 1);
        
        int currentMastery = session.getMasteryScore() != null ? session.getMasteryScore() : score;
        session.setMasteryScore(currentAttemptCount == 0 ? score : (currentMastery + score) / 2);
        
        if (coachDecision == PersonalCoachAttempt.CoachDecision.ADVANCE) {
            session.setStage(PersonalCoachSession.Stage.LESSON_SELECTION);
        }
        sessionRepository.save(session);

        return Map.of(
            "score", score,
            "feedback", attempt.getFeedback(),
            "decision", coachDecision.name(),
            "strengths", normalizeList(parsed.path("strengths")),
            "gaps", normalizeList(parsed.path("gaps"))
        );
    }

    private String serialize(Object obj) {
        try {
            return objectMapper.writeValueAsString(obj);
        } catch (Exception e) {
            return "[]";
        }
    }

    private List<String> normalizeList(JsonNode node) {
        List<String> list = new ArrayList<>();
        if (node.isArray()) {
            for (JsonNode n : node) list.add(n.asText());
        }
        return list;
    }

    private Map<String, List<String>> deserializeMap(String json) {
        if (json == null || json.isEmpty()) return new HashMap<>();
        try {
            return objectMapper.readValue(json, new TypeReference<Map<String, List<String>>>() {});
        } catch (Exception e) {
            return new HashMap<>();
        }
    }

    private List<String> deserializeList(String json) {
        if (json == null || json.isEmpty()) return new ArrayList<>();
        try {
            return objectMapper.readValue(json, new TypeReference<List<String>>() {});
        } catch (Exception e) {
            return new ArrayList<>();
        }
    }

    private List<String> extractLines(String raw) {
        if (raw == null) return new ArrayList<>();
        List<String> lines = new ArrayList<>();
        for (String line : raw.split("\\n")) {
            String cleaned = line.replaceAll("^[-*\\d\\.)\\s]+", "").trim();
            if (!cleaned.isEmpty()) lines.add(cleaned);
        }
        return lines;
    }
}
